title = "NärCon Sommar"
start_date = 2020-07-23
end_date = 2020-07-26
tags = []

[website]
title = "www.narcon.se"
url = "https://www.narcon.se/"

[address]
address = "Linköpings Universitet\nLinköping, Sweden"
city = "Linköping"
country = "Sweden"

[address.coordinates]
lat = 58.398457
lon = 15.574987

