title = "Capital Trade Shows"
start_date = 2020-02-02
end_date = 2020-02-02
tags = []

[website]
title = "capitaltradeshows.com"
url = "http://capitaltradeshows.com/"

[address]
address = "Jim Durrell Recreation Centre\nOttawa, ON\nCanada"
city = "Ottawa, ON"
country = "Canada"

[address.coordinates]
lat = 45.373135
lon = -75.65882

