title = "Ai-Kon"
start_date = 2019-07-26
end_date = 2019-07-28

[website]
title = "ai-kon.org"
url = "https://ai-kon.org"

[address]
address = "RBC Convention Centre\nWinnipeg, MB, Canada\nR3C 3J3"
city = "Winnipeg, MB"

[address.coordinates]
lat = 49.889206
lon = -97.14482
