id = 529
title = "Rai Con Spring"
start_date = 2019-05-04
end_date = 2019-05-04
tags = []

[website]
title = "atticevents.squarespace.com"
url = "https://atticevents.squarespace.com/welcome-to-rai-con-spring/"

[address]
address = "The Glasgow Royal Concert Hall\nGlasgow, UK"
city = "Glasgow"
country = "United Kingdom"

[address.coordinates]
lat = 55.86438
lon = -4.252043

