title = "Gallifrey One"
start_date = 2020-02-14
end_date = 2020-02-16
tags = []

[website]
title = "www.gallifreyone.com"
url = "http://www.gallifreyone.com/"

[address]
address = "Los Angeles Airport Marriott\nLos Angeles, CA\nUSA"
city = "Los Angeles, CA"
country = "USA"

[address.coordinates]
lat = 33.946507
lon = -118.38461

